# Generated by Django 5.0.6 on 2024-06-18 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userfristname', models.TextField(max_length=50)),
                ('userlastname', models.TextField(max_length=50)),
                ('number', models.IntegerField(max_length=10)),
                ('city', models.TextField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('message', models.TextField(max_length=500)),
            ],
            options={
                'verbose_name': 'Register_Data',
                'verbose_name_plural': 'Register_Datas',
            },
        ),
    ]
