# Generated by Django 5.0.6 on 2024-06-18 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_data',
            name='number',
            field=models.IntegerField(),
        ),
    ]
