# Generated by Django 5.0.6 on 2024-06-19 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_1', '0003_rename_userfristname_register_data_userfirstname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_data',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='register_data',
            name='userfirstname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='register_data',
            name='userlastname',
            field=models.CharField(max_length=50),
        ),
    ]
