# Generated by Django 5.0.6 on 2024-06-19 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_1', '0004_alter_register_data_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_data',
            name='number',
            field=models.CharField(max_length=12),
        ),
    ]
