# Generated by Django 5.0.6 on 2024-06-19 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_1', '0005_alter_register_data_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register_data',
            name='message',
        ),
    ]
