# Generated by Django 5.0.6 on 2024-06-19 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_1', '0006_remove_register_data_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userfirstname', models.CharField(max_length=50)),
                ('userlastname', models.CharField(max_length=20)),
                ('number', models.CharField(max_length=12)),
                ('city', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=200)),
                ('regarding', models.TextField(max_length=10)),
            ],
            options={
                'verbose_name': 'Userdata',
                'verbose_name_plural': 'Userdatas',
            },
        ),
        migrations.DeleteModel(
            name='Register_Data',
        ),
    ]
