# Generated by Django 5.0.6 on 2024-06-19 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_1', '0007_userdata_delete_register_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='regarding',
            field=models.TextField(max_length=200),
        ),
    ]
