# Generated by Django 5.0.6 on 2024-06-19 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_1', '0008_alter_userdata_regarding'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='userfirstname',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='userdata',
            old_name='userlastname',
            new_name='lastname',
        ),
    ]
